server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      locator:
        enabled: true
        lower-case-service-id:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/user-service/**
        - id: vaccine-service
          uri: lb://vaccine-service
          predicates:
          - Path=/vaccine-service/**
        - id: openapi
          uri: lb://api-gateway
          predicates:
          - Path=/v3/api-docs/**
          filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs