server:
  port:
    8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #NamingServerURL
resilence4j: #Configuration of Resilience4J (error treatment of requisitions)
  retry:
    instances:
      get-instance:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
spring:
  application:
    name: vaccine-service
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/vaccine_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      dll-auto: update
    show-sql: true
    propertoes:
      hibernate:
        dialect: org.hibernate.dialect.MySQL51nnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: vaccine_service
    user: root
    password: root
springdoc:
  api-docs:
    path: vaccine-service/v3/api-docs
